apiVersion: v2
name: platform-storage
description: A Helm chart for platform-storage service
version: 1.1.0
appVersion: 1.0.0
dependencies:
  - name: k8s-resources
    version: "1.0.1"
    repository: https://neuro-inc.github.io/helm-charts
  - name: admission-controller-lib
    version: "0.1.17"
    repository: https://neuro-inc.github.io/helm-charts
